version: "3.9"

services:
  web:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build:
      context: .
    container_name: celery-worker
    volumes:
      - .:/app
    depends_on:
      - redis
    command: >
      celery -A app.celery.celery_app worker --loglevel=info
  redis:
    image: redis:latest
    container_name: redis
   
